### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by AvidCoder101**
Hi, I have added my name. Thanks (:

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@AkhileshThite

**Review by AkhileshThite — APPROVED** [review]

**Comment by AvidCoder101** [comment]
@AkhileshThite, could I please join the organization?

**Comment by AkhileshThite** [comment]
> @AkhileshThite, could I please join the organization?

Sure. I'll send member invitation.

**Comment by AvidCoder101** [comment]
Thanks (:

**Pull request merged**
